version: "3"

services:
  vote:
    build: ./vote
    volumes:
     - ./vote:/app
    ports:
      - "5000:80"
    networks:
      - front-tier
      - back-tier
    depends_on:
      - "redis"
    command: python app.py

  redis:
    build:
      context: ./redis
    image: redis_voke:alpine
    container_name: redis_vote
    ports: ["6379"]
    networks:
      - back-tier
    environment:
      MY_ENV: 123

# volumes:
#   vote:

networks:
  front-tier:
  back-tier:
