version: "3"

services:
  vote:
    build: ./vote
    command: python app.py
    volumes:
     - ./vote:/app
    ports:
      - "5000:80"
    networks:
      - front-tier
      - back-tier

  redis:
    build:
      context: ./redis
    image: redis_voke:alpine
    container_name: redis
    ports: ["6379"]
    networks:
      - back-tier

# volumes:
#   db-data:

networks:
  front-tier:
  back-tier:
