FROM node:12-alpine
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories
RUN apk add --no-cache bash 
WORKDIR /app
COPY ./app ./
RUN yarn config set registry https://registry.npm.taobao.org/
RUN yarn install --production
CMD ["node", "src/index.js"]