FROM python:3.6-alpine

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories
RUN apk add --no-cache bash && apk add --update bash openssl ca-certificates
RUN pip install pyodbc -i https://mirrors.aliyun.com/pypi/simple/
